export const movies = [
  {
    id: 1,
    title: "The Avengers",
    plot: "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BNDYxNjQyMjAtNTdiOS00NGYwLWFmNTAtNThmYjU5ZGI2YTI1XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
    rating: "8.0",
    price: 99,
    star: 0,
    fav: false,
    isInCart: false,
  },
  {
    id: 2,
    title: "The Dark Knight",
    plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg",
    rating: "9.0",
    price: 199,
    star: 0,
    fav: false,
    isInCart: false,
  },
  {
    id: 3,
    title: "Iron Man",
    plot: "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
    poster:
      "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_SX300.jpg",
    rating: "7.9",
    price: 139,
    star: 0,
    fav: false,
    isInCart: false,
  },
  {
    id: 4,
    title: "The Platform",
    plot: 'The film is set in a large, tower-style "Vertical Self-Management Center."',
    poster:
      "https://upload.wikimedia.org/wikipedia/en/5/54/The_Platform_poster.jpg",
    rating: "8.9",
    price: 150,
    star: 0,
    fav: false,
    isInCart: false,
  },
  {
    id: 5,
    title: "Parasite ",
    plot: "The film's shocking twist reveals a hidden man living in the Park family's basement, leading to chaos and bloodshed. Parasite offers a bleak and realistic ending, highlighting the idea of wealth as a prison and economic immobility as the new norm.",
    poster:
      "https://upload.wikimedia.org/wikipedia/en/5/53/Parasite_%282019_film%29.png",
    rating: "7.9",
    price: 170,
    star: 0,
    fav: false,
    isInCart: false,
  },
  {
    id: 6,
    title: "The Menu ",
    plot: "It follows a foodie and his date traveling to a remote island to eat at an exclusive restaurant where the chef has prepared a lavish menu but reveals shocking surprises throughout the meal.",
    poster:
      "https://upload.wikimedia.org/wikipedia/en/d/db/The_Menu_%282022_film%29.jpg",
    rating: "7.1",
    price: 140,
    star: 0,
    fav: false,
    isInCart: false,
  },
  {
    id: 7,
    title: "Red Sparrow",
    plot: "It tells the story of a former ballerina turned Russian intelligence officer, who is sent to make contact with a CIA officer in the hope of discovering the identity of a mole.",
    poster: "https://upload.wikimedia.org/wikipedia/en/5/5a/Red_Sparrow.png",
    rating: "6.9",
    price: 120,
    star: 0,
    fav: false,
    isInCart: false,
  },
];
